trigger:
  branches:
    include:
    - master
    paths:
      include:
        - /back-end/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Run back-end build
  displayName: 'back-end build'